services:
  - type: web
    name: dmg-bot
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: GUILD_ID
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: DISCORD_REDIRECT_URI
        sync: false
      - key: ADMIN_ROLE_IDS
        sync: false
      - key: ADMIN_USER_IDS
        sync: false
